language: python
python:
  - "3.11"
install:
  - pip install -r requirements.txt
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>="
  secret_access_key:
    secure: "Encrypted <secret-access-key>="
  region: "us-east-1"
  app: "<app-name>"
  env: "<env-name>"
  bucket_name: "bucket-name"