language: python
python:
  - "3.11"
install:
  - pip install -r requirements.txt
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>=AKIA4DMVQ37SJJKN4BEO"
  secret_access_key:
    secure: "Encrypted <secret-access-key>=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"
  region: "us-east-1"
  app: "django-polls"
  env: "django-polls-env"
  bucket_name: "bucket-name"