language: python
python:
  - 3.9
install:
  - pip install -r requirements.txt
script:
  - black --check ebdjango
  - black --check polls
  - flake8 ebdjango
  - flake8 polls
  - coverage run manage.py test polls
  - coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ID
  secret_access_key:
    secure: $AWS_KEY
  region: "us-east-1"
  app: "ebdjango"
  env: "ebdjango-dev"
  bucket_name: "elasticbeanstalk-us-east-1-831926624228"
  on:
    repo: SamuelVRPO/sv2657-polls
    branch:
      only:
        - main